load("//tools/build_defs/oss:screenshot_test_defs.bzl", "SCREENSHOT_TESTS_CORE_TARGET", "SCREENSHOT_TESTS_LITHO_CORE_TARGET", "SCREENSHOT_TESTS_LITHO_WIDGET_TARGET", "SCREENSHOT_TESTS_VISIBILITY", "fb_core_android_library")

fb_core_android_library(
    name = "litho",
    srcs = glob(["**/*.java"]),
    visibility = SCREENSHOT_TESTS_VISIBILITY,
    deps = [
        SCREENSHOT_TESTS_CORE_TARGET,
        SCREENSHOT_TESTS_LITHO_CORE_TARGET,
        SCREENSHOT_TESTS_LITHO_WIDGET_TARGET,
    ],
)
