# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

java_library(
    name = "junit",
    exported_deps = [
        ":junit-prebuilt",
    ],
    visibility = ["PUBLIC"],
)

prebuilt_jar(
    name = "junit-prebuilt",
    binary_jar = ":junit.jar",
    visibility = ["PUBLIC"],
)

remote_file(
    name = "junit.jar",
    sha1 = "2973d150c0dc1fefe998f834810d68f278ea58ec",
    url = "mvn:junit:junit:jar:4.12",
)
