# Copyright 2014-present Facebook, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("@fbsource//tools/build_defs/android:fb_java_library.bzl", "fb_java_library")

fb_java_library(
    name = "junit",
    visibility = ["PUBLIC"],
    exported_deps = [
        ":junit-prebuilt",
    ],
)

fb_native.prebuilt_jar(
    name = "junit-prebuilt",
    binary_jar = ":junit.jar",
    visibility = ["PUBLIC"],
)

fb_native.remote_file(
    name = "junit.jar",
    sha1 = "2973d150c0dc1fefe998f834810d68f278ea58ec",
    url = "mvn:junit:junit:jar:4.12",
)
