# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

load("//:SCREENSHOT_TESTS_DEFS", "SCREENSHOT_TESTS_CORE_TARGET", "SCREENSHOT_TESTS_VISIBILITY")

android_library(
    name = "common",
    srcs = glob(["**/*.java"]),
    visibility = SCREENSHOT_TESTS_VISIBILITY,
    deps = [
        SCREENSHOT_TESTS_CORE_TARGET,
    ],
)
