permalink: /blog/:year/:month/:day/:title.html
title: screenshot-tests-for-android
tagline: Automated testing that helps prevent visual regressions in Android apps
fbappid: ""
description:
baseurl: /screenshot-tests-for-android
url: https://facebook.github.io
ghrepo: "facebook/screenshot-tests-for-android"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false

exclude: [README.md, Gemfile, scripts, vendor]
keep_files: [.git, .hg]

collections:
  docs:
    output: true
    permalink: /docs/:name/

sass:
  style: :compressed

redcarpet:
  extensions: [with_toc_data, no_intra_emphasis, tables, autolink]

gacode: "UA-44373548-12"
color:
  primary: "#9e2b07"
  secondary: "#fff"
  light: "#de4d1f"
  lighttext: "#fff"
  headertext: "#fff"
  bodytext: "#151515"
  nav: "#8a2100"
  navtext: "#ed8564"
  link: "#de4d1f"
