load("//tools/build_defs/oss:screenshot_test_defs.bzl", "SCREENSHOT_TESTS_CORE_TARGET", "SCREENSHOT_TESTS_LAYOUT_HIERARCHY_COMMON_TARGET", "SCREENSHOT_TESTS_LAYOUT_HIERARCHY_LITHO_TARGET", "SCREENSHOT_TESTS_VISIBILITY", "fb_core_android_library")

fb_core_android_library(
    name = "screenshot",
    visibility = SCREENSHOT_TESTS_VISIBILITY,
    deps = [
        SCREENSHOT_TESTS_CORE_TARGET,
        SCREENSHOT_TESTS_LAYOUT_HIERARCHY_COMMON_TARGET,
        SCREENSHOT_TESTS_LAYOUT_HIERARCHY_LITHO_TARGET,
    ],
    exported_deps = [
        SCREENSHOT_TESTS_CORE_TARGET,
        SCREENSHOT_TESTS_LAYOUT_HIERARCHY_COMMON_TARGET,
        SCREENSHOT_TESTS_LAYOUT_HIERARCHY_LITHO_TARGET,
    ],
)
