# Copyright 2014-present Facebook, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/oss:screenshot_test_defs.bzl", "fb_core_android_library")

fb_core_android_library(
    name = "litho-core",
    visibility = ["PUBLIC"],
    exported_deps = [
        ":litho-core-prebuilt",
    ],
)

fb_native.android_prebuilt_aar(
    name = "litho-core-prebuilt",
    aar = ":litho-core.aar",
    visibility = ["PUBLIC"],
)

fb_native.remote_file(
    name = "litho-core.aar",
    sha1 = "76ec5c2f13063cc2698b7c1c430b91af8f59fab4",
    url = "mvn:com.facebook.litho:litho-core:aar:0.7.0",
)

fb_core_android_library(
    name = "litho-widget",
    visibility = ["PUBLIC"],
    exported_deps = [
        ":litho-widget-prebuilt",
    ],
)

fb_native.android_prebuilt_aar(
    name = "litho-widget-prebuilt",
    aar = ":litho-widget.aar",
    visibility = ["PUBLIC"],
)

fb_native.remote_file(
    name = "litho-widget.aar",
    sha1 = "2b16fcb64582263fa7cb1803ffd6ced74ba7422a",
    url = "mvn:com.facebook.litho:litho-widget:aar:0.7.0",
)
