load("//tools/build_defs/oss:screenshot_test_defs.bzl", "SCREENSHOT_TESTS_VISIBILITY", "fb_core_android_library")

fb_core_android_library(
    name = "screenshot",
    srcs = glob(["**/*.java"]),
    k2 = True,
    visibility = SCREENSHOT_TESTS_VISIBILITY,
    deps = [
        "//fbandroid/third-party/java/infer-annotations:infer-annotations",
        "//third-party/java/androidx/annotation/annotation:annotation",
        "//third-party/java/androidx/core/core:core",
        "//third-party/java/com/google/code/findbugs/jsr305:jsr305",
        "//third-party/java/com/google/code/gson/gson:gson",
        "//third-party/java/com/google/guava/guava:guava",
    ],
)
