load("//tools/build_defs/oss:screenshot_test_defs.bzl", "SCREENSHOT_TESTS_VISIBILITY", "fb_core_android_library")

fb_core_android_library(
    name = "screenshot",
    srcs = glob(["**/*.java"]),
    is_androidx = False,
    visibility = SCREENSHOT_TESTS_VISIBILITY,
    deps = [
        "//fbandroid/third-party/android/androidx:support-v4",
        "//fbandroid/third-party/java/jsr-305:jsr-305",
    ],
)
