load("@fbsource//tools/build_defs:fb_python_library.bzl", "fb_python_library")

fb_python_library(
    name = "android_screenshot_tests",
    srcs = glob(["android_screenshot_tests/**/*.py"]),
    base_module = "",
    visibility = ["PUBLIC"],
)
