load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

fb_native.python_library(
    name = "android_screenshot_tests",
    srcs = glob(["android_screenshot_tests/**/*.py"]),
    base_module = "",
    visibility = ["PUBLIC"],
)
